# Generated by Django 4.0.3 on 2022-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_category_options_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
